baseURL: "https://palestamp.github.io/blog/"
languageCode: "en-us"
title: "Midnight Provolone"
theme: "simple-style"
author: "Stas Kazhavets"
copyright: "&copy; {currentYear} Stas Kazhavets."
googleAnalyticsID: "G-5Y96G1EZM4"