baseURL: "https://palestamp.github.io/blog/"
languageCode: "en-us"
title: "Midnight Provolone"
theme: "simple-style"
author: "Stas Kazhavets"
copyright: "&copy; {currentYear} Stas Kazhavets."

markup:
  highlight:
    style: github
  goldmark:
    renderer:
      unsafe: true